apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gearpit-ingress
spec:
  rules:
    - host: gearpit.localhost
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gearpit-app-svc
                port:
                  number: 80