apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - service-local.yaml
images:
  - name: ghcr.io/nordiwnd/gearpit-app
    newName: gearpit-app
patches:
  - path: patch-deploy.yaml
  - path: patch-db-svc.yaml
