apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- test-deploy.yaml
- ingress.yaml

images:
- name: ghcr.io/nordiwnd/gearpit-app
  newName: ghcr.io/nordiwnd/gearpit-app
  newTag: 1f06302
