apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# CI/CDによって自動更新される画像タグ
images:
- name: ghcr.io/nordiwnd/gearpit-app
  newName: ghcr.io/nordiwnd/gearpit-app
  newTag: 0c904b19e54840e399174968c0f6566bce9b6c47
