apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# CI/CDによって自動更新される画像タグ
images:
- name: ghcr.io/nordiwnd/gearpit-app
  newName: ghcr.io/nordiwnd/gearpit-app
  newTag: 989356bc985c8828dc7297f6cadb605de53a1753
