apiVersion: apps/v1
kind: Deployment
metadata:
  name: gearpit-web
  labels:
    app: gearpit-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gearpit-web
  template:
    metadata:
      labels:
        app: gearpit-web
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: web
          image: ghcr.io/nordiwnd/gearpit-web:latest
          ports:
            - containerPort: 3000
          env: # 追加
            - name: NEXT_PUBLIC_API_URL
              value: "http://gearpit.local/api"