apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gearpit-web-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: gearpit.192.168.40.100.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gearpit-web-svc
                port:
                  number: 80