apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-deploy.yaml
  - path: ingress.yaml
images:
  - name: ghcr.io/nordiwnd/gearpit-web
    newName: gearpit-web
