apiVersion: apps/v1
kind: Deployment
metadata:
  name: gearpit-app
  labels:
    app: gearpit-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gearpit-app
  template:
    metadata:
      labels:
        app: gearpit-app
    spec:
      # imagePullSecrets:
      #   - name: ghcr-creds
      containers:
        - name: app
          image: ghcr.io/nordiwnd/gearpit-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: DB_HOST
              value: "postgres-postgresql.default.svc.cluster.local"
            - name: DB_USER
              value: "gearpit"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "gearpit"
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: gearpit-app-svc
spec:
  selector:
    app: gearpit-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080