apiVersion: apps/v1
kind: Deployment
metadata:
  name: gearpit-app
  labels:
    app: gearpit-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gearpit-app
  template:
    metadata:
      labels:
        app: gearpit-app
    spec:
      containers:
        - name: app
          image: ghcr.io/nordiwnd/gearpit-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            # DB接続情報 (Base/本番用)
            - name: DB_USER
              value: "gearpit"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "gearpit"
            - name: DB_HOST
              value: "gearpit-db-svc" 
            - name: DB_PORT
              value: "5432"
            - name: SSL_MODE
              value: "disable"
