apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gearpit-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    # 追加: replaceパッチを機能させるためのプレースホルダー
    - host: gearpit.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gearpit-svc
                port:
                  number: 80