---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: previewenvs.core.gearpit.io
spec:
  group: core.gearpit.io
  names:
    kind: PreviewEnv
    listKind: PreviewEnvList
    plural: previewenvs
    singular: previewenv
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.prNumber
      name: PR
      type: integer
    - jsonPath: .status.url
      name: URL
      type: string
    - jsonPath: .status.available
      name: Available
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PreviewEnv is the Schema for the previewenvs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PreviewEnvSpec defines the desired state of PreviewEnv
            properties:
              imageTag:
                description: ImageTag is the container image tag to deploy.
                minLength: 1
                type: string
              includeDB:
                default: true
                description: IncludeDB determines whether to provision a dedicated
                  database.
                type: boolean
              prNumber:
                description: PRNumber is the pull request number.
                minimum: 1
                type: integer
            required:
            - imageTag
            - prNumber
            type: object
          status:
            description: PreviewEnvStatus defines the observed state of PreviewEnv
            properties:
              available:
                description: Available indicates if the deployment is ready.
                type: boolean
              url:
                description: URL is the generated access point.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
